# Generated by Django 3.0.3 on 2023-02-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField(max_length=10)),
                ('attempts_left', models.IntegerField()),
                ('Selected_word', models.TextField()),
                ('word_progress', models.TextField()),
            ],
        ),
    ]
