# Generated by Django 3.0.3 on 2023-02-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Selected_word',
            field=models.TextField(default='random'),
        ),
        migrations.AlterField(
            model_name='game',
            name='attempts_left',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='game',
            name='word_progress',
            field=models.TextField(default='set_progress'),
        ),
    ]
