# Generated by Django 3.0.3 on 2023-02-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230208_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='actualGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_word', models.TextField()),
                ('attempts_left', models.IntegerField(default=7)),
                ('word_length', models.IntegerField(default=0)),
                ('attemptDone', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='Selected_word',
        ),
        migrations.RemoveField(
            model_name='game',
            name='attempts_left',
        ),
        migrations.RemoveField(
            model_name='game',
            name='word_progress',
        ),
    ]
